# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/rhel8"
  config.vm.box_check_update = false

   config.vm.hostname = "serverA"
   config.ssh.username = "vagrant"
   config.ssh.password = "root"
   config.ssh.insert_key = false
   config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
     vb.cpus = 2
   end
end
