Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
  #Ansible Master Node###
  config.vm.define "ansible" do |ansible|
    config.vm.box = "geerlingguy/centos7"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    config.vm.provision "shell" do |s|
      p = File.expand_path("../", __FILE__)
      s.path = p + "\\workstation.sh"
    end 
    ansible.vm.hostname = "ansible-master"
    ansible.vm.network "private_network", ip: "192.168.56.11"
  end
  #Ansible Slave Node 01#
  config.vm.define "ansbile slave 01" do |as01|
    config.vm.box = "geerlingguy/centos7"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    config.vm.provision "shell" do |s|
      p = File.expand_path("../", __FILE__)
      s.path = p + "\\client.sh"
    end 
    as01.vm.hostname ="ansible-slave1"
    as01.vm.network "private_network", ip: "192.168.56.12"
  end
  #Ansible Slave Node 02#
  config.vm.define "ansible slave 02" do |as02|  
    config.vm.box = "geerlingguy/centos7"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end 
    config.vm.provision "shell" do |s|
      p = File.expand_path("../", __FILE__)
      s.path = p + "\\client.sh"
    end    
      as02.vm.hostname ="ansible-slave2"
      as02.vm.network "private_network", ip: "192.168.56.13"
  end  
  #Ansible Slave Node 03#
  config.vm.define "ansible slave 03" do |as03|
    config.vm.box = "geerlingguy/centos7"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    config.vm.provision "shell" do |s|
      p = File.expand_path("../", __FILE__)
      s.path = p + "\\client.sh"
    end 
    as03.vm.hostname ="ansible-slave4"
    as03.vm.network "private_network", ip: "192.168.56.14"
  end    
end  